pipeline: 
  build:
    image: golang
    commands:
      - go env
      - export GOBIN=$GOPATH/bin
      - go get
      - go get github.com/smartystreets/goconvey/convey
      - go build
      - go test -v ./... 